### ISSUE TITLE
Error in 'scan' method when used gem Faker

### ISSUE THREAD

**Issue by marciojg** [NachoPal/dry_i18n#3]
When I use the command of gem Faker
```
Faker::Name.title.parameterize.underscore 
```
return this error:
```
NoMethodError: undefined method `scan' for #<Array:0x000055bbb332ba80>
from /usr/local/bundle/gems/dry_i18n-1.0.0/lib/dry_i18n.rb:31:in `variables?'
```

Complete error in console

```
NoMethodError:
       undefined method `scan' for #<Array:0x000055e5966ff398>
     # /usr/local/bundle/gems/dry_i18n-1.0.0/lib/dry_i18n.rb:31:in `variables?'
     # /usr/local/bundle/gems/dry_i18n-1.0.0/lib/dry_i18n.rb:10:in `translate'
     # /usr/local/bundle/gems/i18n-0.9.5/lib/i18n.rb:169:in `block in translate'
     # /usr/local/bundle/gems/i18n-0.9.5/lib/i18n.rb:165:in `catch'
     # /usr/local/bundle/gems/i18n-0.9.5/lib/i18n.rb:165:in `translate'
     # /usr/local/bundle/gems/faker-1.8.7/lib/faker.rb:157:in `rescue in translate'
     # /usr/local/bundle/gems/faker-1.8.7/lib/faker.rb:145:in `translate'
     # /usr/local/bundle/gems/faker-1.8.7/lib/faker.rb:98:in `fetch'
     # /usr/local/bundle/gems/faker-1.8.7/lib/faker/name.rb:34:in `title'
     # ./spec/factories/configuration.rb:5:in `block (3 levels) in <main>'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/attribute/dynamic.rb:16:in `instance_exec'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/attribute/dynamic.rb:16:in `block in to_proc'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/evaluator.rb:77:in `instance_exec'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/evaluator.rb:77:in `block in define_attribute'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/attribute_assigner.rb:56:in `get'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/attribute_assigner.rb:16:in `block (2 levels) in object'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/attribute_assigner.rb:15:in `each'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/attribute_assigner.rb:15:in `block in object'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/attribute_assigner.rb:14:in `tap'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/attribute_assigner.rb:14:in `object'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/evaluation.rb:13:in `object'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/strategy/create.rb:9:in `result'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/factory.rb:43:in `run'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/factory_runner.rb:29:in `block in run'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/factory_runner.rb:28:in `run'
     # /usr/local/bundle/gems/factory_bot-4.8.2/lib/factory_bot/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
     # ./spec/models/configuration_spec.rb:5:in `block (2 levels) in <main>'
     # ./spec/models/configuration_spec.rb:12:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # I18n::MissingTranslationData:
     #   translation missing: pt-BR.faker.name.title.descriptor
     #   /usr/local/bundle/gems/i18n-0.9.5/lib/i18n.rb:326:in `handle_exception'
```

@NachoPal  Can help?

**Comment by pedrofurtado** [comment]
@NachoPal 

The library has not the correct behavior when the variable `translation` inside source code returns something different of String. I created a a pull request for this explaining the fix: https://github.com/NachoPal/dry_i18n/pull/4

**Comment by marciojg** [comment]
Nice! Thanks all! 

@NachoPal , now you can reference this new merge in repository in rubygems?

**Comment by NachoPal** [comment]
@marcioJesus , @pedrofurtado , @MiguelSavignano 

New version in https://rubygems.org/gems/dry_i18n

Let me know if everything is alright

**Comment by pedrofurtado** [comment]
@NachoPal Thanks man! Here worked well. Thanks again!

**Comment by marciojg** [comment]
@NachoPal Here worked well too.

Thanks man!
